<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import YkPageHeader from '../../components/common/YkPageHeader.vue'
import { gradingApi, type ApiError } from '../api'

const route=useRoute(),page=computed(()=>String(route.meta.page||'grades'))
const loading=ref(true),downloading=ref(''),error=ref(''),policy=ref<any>({items:[]}),book=ref<any>({items:[]}),overview=ref<any>({}),section=ref<any>({}),labsStudent=ref<any>({items:[]}),labsLab=ref<any>({items:[]}),risks=ref<any>({items:[]}),archive=ref<any>({}),student=ref<any>({}),audits=ref<any>({items:[]}),trace=ref<any|null>(null),tab=ref('overview')
const titles:any={grades:['成绩管理','签到、作业、测验、实验与互动统一计算，每一分都能追溯到上游事实。'],analytics:['学情分析','课程总览、按小节、实验双维全部由成绩事实计算。'],archive:['课程归档','冻结成绩、资源引用、实验证据与学情产物，不删除历史事实。'],student:['我的成绩','只显示本人已入账成绩、来源与风险提示。'],audit:['审计日志','高风险动作只追加、可筛选、可导出，不提供修改或删除入口。']}
const statusText=(value:string)=>({PENDING:'待处理',PARTIAL:'部分数据',READY:'就绪',POSTED:'已入账',LOCKED:'已锁定',PRECHECK:'预检中',ARCHIVED:'已归档',PUBLISHED:'已发布'} as any)[value]||'未知状态'
const componentText=(value:string)=>({ATTENDANCE:'签到',ASSIGNMENT:'作业',QUIZ:'测验',LAB:'实验',INTERACTION:'互动',LAB_SUBMISSION:'实验提交',LAB_CHECKPOINT:'实验检查点'} as any)[value]||'其他来源'
const checkText=(value:string)=>({roster_frozen:'学生名单已冻结',roster_student_count_matches:'名单人数与成绩册一致',gradebook_posted:'成绩已入账',grade_event_traceable:'成绩来源可追溯',lab_evidence_referenced:'实验判分证据已引用',resources_frozen:'课程资源已冻结'} as any)[value]||'其他归档检查'
const actionText=(value:string)=>({GRADEBOOK_RECALCULATED:'成绩册已重算',GRADEBOOK_POSTED:'成绩已入账',COURSE_ARCHIVE_PRECHECK:'课程归档预检',COURSE_ARCHIVED:'课程已归档',RUNTIME_INSTANCE_DESTROYED:'运行实例已销毁'} as any)[value]||'其他操作'
const resourceTypeText=(value:string)=>({gradebook:'成绩册',course_archive:'课程归档',runtime_instance:'运行实例',grading_policy:'成绩规则',grade_event:'成绩事实'} as any)[value]||'业务对象'
const resultText=(value:string)=>({SUCCESS:'成功',BLOCKED:'已阻断',ERROR:'错误'} as any)[value]||'未知结果'
const artifactText=(value:string)=>({GRADEBOOK_XLSX:'成绩册 XLSX（电子表格）',ANALYTICS_XLSX:'学情 XLSX（电子表格）',RESOURCE_VERSION_MANIFEST_JSON:'资源版本清单 JSON（数据文件）',LAB_EVIDENCE_REFERENCES:'实验日志与判分证据引用'} as any)[value]||'其他归档产物'
const artifactFilename=(value:string)=>({GRADEBOOK_XLSX:'课程归档成绩册.xlsx',ANALYTICS_XLSX:'课程归档学情.xlsx',RESOURCE_VERSION_MANIFEST_JSON:'课程资源版本清单.json'} as any)[value]||'课程归档产物.bin'
const riskText=(value:string)=>({LOW_ATTENDANCE:'到课率偏低',LOW_TOTAL_SCORE:'总评偏低',MISSING_FACTS:'教学事实不完整',CONSECUTIVE_CHECKPOINT_FAILURES:'实验检查点连续失败',MULTIPLE_MISSING_SUBMISSIONS:'多次实验未提交'} as any)[value]||'其他学习风险'
async function load(){loading.value=true;error.value='';trace.value=null;try{
  if(page.value==='grades')[policy.value,book.value]=await Promise.all([gradingApi.policy(),gradingApi.gradebook()])
  if(page.value==='analytics')[overview.value,section.value,labsStudent.value,labsLab.value,risks.value]=await Promise.all([gradingApi.overview(),gradingApi.section(),gradingApi.labsStudent(),gradingApi.labsLab(),gradingApi.risks()])
  if(page.value==='archive')archive.value=await gradingApi.archive()
  if(page.value==='student')student.value=await gradingApi.studentScore()
  if(page.value==='audit')audits.value=await gradingApi.audit()
}catch(reason){error.value=(reason as ApiError).message||'服务暂时不可用'}finally{loading.value=false}}
async function recalc(){try{book.value=await gradingApi.recalculate();await load()}catch(reason){error.value=(reason as ApiError).message}}
async function post(){if(!confirm('确认将当前成绩正式入账？入账后不能静默修改。'))return;try{await gradingApi.post();await load()}catch(reason){error.value=(reason as ApiError).message}}
async function showTrace(id:string){try{trace.value=await gradingApi.trace(id)}catch(reason){error.value=(reason as ApiError).message}}
async function precheck(){try{archive.value={status:'PRECHECK',precheck:await gradingApi.precheck()}}catch(reason){error.value=(reason as ApiError).message}}
async function freeze(){if(!confirm('确认冻结课程归档？成绩册将锁定。'))return;try{await gradingApi.freeze();await load()}catch(reason){error.value=(reason as ApiError).message}}
async function saveDownload(key:string,filename:string,request:()=>Promise<Blob>){try{downloading.value=key;error.value='';const blob=await request();const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),0)}catch(reason){error.value=(reason as ApiError).message||'文件下载失败'}finally{downloading.value=''}}
onMounted(load);watch(page,load)
</script>
<template><div>
  <YkPageHeader :title="titles[page][0]" :description="titles[page][1]"><template #actions><div class="actions"><button v-if="page==='grades'" class="yk-button" @click="saveDownload('gradebook','成绩册.xlsx',gradingApi.gradebookExport)">导出成绩册</button><button v-if="page==='grades'" class="yk-button" @click="recalc">重新计算</button><button v-if="page==='grades'" class="yk-button primary" @click="post">确认成绩入账</button><button v-if="page==='analytics'" class="yk-button" @click="saveDownload('analytics','学情分析.xlsx',gradingApi.analyticsExport)">导出学情</button><button v-if="page==='archive'" class="yk-button" @click="precheck">归档预检</button><button v-if="page==='archive'" class="yk-button primary" @click="freeze">冻结归档</button></div></template></YkPageHeader>
  <div v-if="loading" class="state-panel">正在读取成绩事实…</div><div v-else-if="error" class="state-panel error-state"><b>操作未完成</b><span>{{error}}</span><button class="yk-button" @click="load">重试</button></div>
  <template v-else-if="page==='grades'">
    <div class="grid grid-2"><div class="card"><h3>总评权重</h3><div v-if="!policy.items?.length" class="empty-cell">成绩规则尚未发布</div><div v-for="item in policy.items" :key="item.component" class="weight-row"><span>{{componentText(item.component)}}</span><div class="bar"><i :style="{width:item.weight_percent+'%'}"></i></div><b>{{item.weight_percent}}%</b></div></div><div class="card"><h3>班级结果</h3><div class="score-hero">{{book.status==='PENDING'?'待计算':statusText(book.status)}}</div><p class="muted">规则版本：{{book.policy_version||'—'}} · 所有正式成绩均由后端计算</p></div></div>
    <div class="card table-card"><table class="data-table"><thead><tr><th>学生</th><th>总评</th><th>完整性</th><th>来源</th></tr></thead><tbody><tr v-for="item in book.items" :key="item.student_id"><td>{{item.student_id}}</td><td><b>{{item.total_score}}</b></td><td><span class="badge">{{statusText(item.completeness)}}</span></td><td><button class="yk-button" @click="showTrace(item.student_id)">追溯</button></td></tr><tr v-if="!book.items?.length"><td colspan="4" class="empty-cell">等待 A/D/E 上游教学事实</td></tr></tbody></table></div>
    <div v-if="trace" class="card trace-card"><h3>成绩来源追溯 · {{trace.student_id}}</h3><p>总评 {{trace.total_score}} · 规则版本 {{trace.policy_version}}</p><div v-for="component in trace.components" :key="component.component" class="trace-row"><b>{{componentText(component.component)}} {{component.weight_percent}}%</b><span>{{component.score}} × {{component.weight_percent}}% = {{component.weighted_score}}</span><small v-for="source in component.sources" :key="source.event_id">{{componentText(source.source_type)}} · 来源 {{source.source_id}} · {{source.normalized_score}} 分 · {{source.occurred_at}}</small></div></div>
  </template>
  <template v-else-if="page==='analytics'">
    <div class="analytics-tabs"><button :class="{active:tab==='overview'}" @click="tab='overview'">① 课程总览</button><button :class="{active:tab==='section'}" @click="tab='section'">② 按小节</button><button :class="{active:tab==='lab'}" @click="tab='lab'">③ 实验维度</button></div>
    <template v-if="tab==='overview'"><div class="grid grid-4 summary-grid"><div class="card kpi"><span>作业平均</span><b>{{overview.avg_assignment??'—'}}</b></div><div class="card kpi"><span>测验平均</span><b>{{overview.avg_quiz??'—'}}</b></div><div class="card kpi"><span>平均到课率</span><b>{{overview.attendance_rate??'—'}}</b></div><div class="card kpi"><span>课程班均</span><b>{{overview.course_average??'—'}}</b></div></div><div class="card"><h3>学习风险</h3><div v-if="!risks.items?.length" class="empty-cell">当前没有学习风险</div><div v-for="risk in risks.items" :key="risk.student_risk_flag_id" class="check-row"><b>{{risk.student_id}}</b><span>{{riskText(risk.risk_type)}}</span><em>待跟进</em></div></div></template>
    <div v-if="tab==='section'" class="card"><h3>小节成绩分布</h3><p>平均成绩：{{section.average??'—'}}</p><div v-for="(count,range) in section.distribution" :key="range" class="weight-row"><span>{{range}}</span><div class="bar"><i :style="{width:(Number(count)*10)+'%'}"></i></div><b>{{count}} 人</b></div><div v-if="section.status==='PENDING'" class="empty-cell">等待小节成绩事实</div></div>
    <div v-if="tab==='lab'" class="grid grid-2"><div class="card"><h3>学生维度</h3><table class="data-table"><thead><tr><th>学生</th><th>实验总分</th><th>已提交</th><th>未提交</th></tr></thead><tbody><tr v-for="x in labsStudent.items" :key="x.student_id"><td>{{x.student_id}}</td><td>{{x.sum_lab_score}}</td><td>{{x.submitted_count}}</td><td>{{x.unsubmitted_count}}</td></tr></tbody></table></div><div class="card"><h3>实验维度</h3><table class="data-table"><thead><tr><th>实验</th><th>平均</th><th>已提交</th><th>未提交</th></tr></thead><tbody><tr v-for="x in labsLab.items" :key="x.lab_release_id"><td>{{x.lab_release_id}}</td><td>{{x.avg_score}}</td><td>{{x.submitted_students}}</td><td>{{x.unsubmitted_students}}</td></tr></tbody></table></div></div>
  </template>
  <template v-else-if="page==='archive'"><div class="grid grid-2"><div class="card"><h3>归档门禁</h3><div v-if="!archive.precheck" class="empty-cell">点击“归档预检”读取真实门禁</div><div v-for="(passed,key) in archive.precheck?.checks" :key="key" class="check-row"><span>{{passed?'✓':'!'}}</span><b>{{checkText(String(key))}}</b><em>{{passed?'通过':'阻断'}}</em></div></div><div class="card"><h3>归档产物</h3><div v-if="!archive.manifest?.artifacts?.length" class="empty-cell">归档冻结后生成不可变产物</div><div v-for="artifact in archive.manifest?.artifacts" :key="artifact.type" class="check-row"><b>{{artifactText(artifact.type)}}</b><button v-if="artifact.evidence_ref?.startsWith('/api/')" class="yk-button" :data-testid="'archive-download-'+artifact.type" :disabled="downloading===artifact.type" @click="saveDownload(artifact.type,artifactFilename(artifact.type),()=>gradingApi.archiveArtifact(artifact.type))">{{downloading===artifact.type?'正在下载…':'下载并校验'}}</button><em v-else>已固化引用</em></div><p class="badge">{{statusText(archive.status||'PENDING')}}</p></div></div></template>
  <template v-else-if="page==='student'"><div class="grid grid-4 summary-grid"><div class="card kpi"><span>学习摘要状态</span><b>{{statusText(student.status)}}</b></div><div class="card kpi"><span>本人总评</span><b>{{student.grade?.items?.[0]?.total_score??'—'}}</b></div><div class="card kpi"><span>风险提示</span><b>{{student.risk?.items?.length??0}}</b></div><div class="card kpi"><span>班级排行</span><b>{{student.analytics?.student_rank??'—'}}</b></div></div><div class="card blockers" v-if="student.missing_upstream?.length"><h3>尚待上游事实</h3><p v-for="x in student.missing_upstream" :key="x">{{x}}</p></div></template>
  <template v-else-if="page==='audit'"><div class="card table-card"><div class="actions"><button class="yk-button" @click="saveDownload('audit-xlsx','审计日志.xlsx',()=>gradingApi.auditExport('xlsx'))">导出 XLSX（电子表格）</button><button class="yk-button" @click="saveDownload('audit-csv','审计日志.csv',()=>gradingApi.auditExport('csv'))">导出 CSV（逗号分隔文件）</button></div><table class="data-table"><thead><tr><th>时间</th><th>操作者</th><th>动作</th><th>对象</th><th>结果</th><th>原因</th></tr></thead><tbody><tr v-for="x in audits.items" :key="x.audit_event_id"><td>{{x.occurred_at}}</td><td>{{x.actor_user_id}} / {{x.actor_role==='teacher'?'教师':x.actor_role==='student'?'学生':x.actor_role==='admin'?'管理员':'系统服务'}}</td><td>{{actionText(x.action)}}</td><td>{{resourceTypeText(x.resource_type)}} · {{x.resource_id}}</td><td><span class="badge">{{resultText(x.result)}}</span></td><td>{{x.reason||'—'}}</td></tr><tr v-if="!audits.items?.length"><td colspan="6" class="empty-cell">尚无审计事件</td></tr></tbody></table></div></template>
</div></template>
