<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { classroomApi, type ApiError } from '../../app/api'
import YkDrawer from '../../components/common/YkDrawer.vue'
import YkTabs from '../../components/common/YkTabs.vue'
import YkSelect from '../../components/common/YkSelect.vue'
import TerminalPanel from './TerminalPanel.vue'
type Student={student_id:string;student_name:string;student_no?:string;status:string;current_step:number;total_steps:number;raw_score:number;max_score:number;runtime_instance_id?:string}
type Summary={started:number;completed:number;running:number;failed:number;not_started:number}
const releaseId=ref(localStorage.getItem('yk-release-id')||'release-1'), summary=ref<Summary|null>(null), students=ref<Student[]>([]), error=ref(''), loading=ref(true), filter=ref('ALL'), query=ref(''), selected=ref<Student|null>(null), detail=ref<any>(null), tab=ref('steps'), busy=ref('')
const filtered=computed(()=>students.value.filter(x=>(filter.value==='ALL'||x.status===filter.value)&&(`${x.student_name}${x.student_no||''}`).includes(query.value)))
const label=(status:string)=>({RUNNING:'进行中',SUBMITTED:'已提交',COMPLETED:'已完成',FAILED:'异常',NOT_STARTED:'未开始'}[status]||status)
async function load(){loading.value=true;error.value='';try{const [s,l]=await Promise.all([classroomApi<Summary>(`/api/v1/classroom/lab-releases/${releaseId.value}/summary`),classroomApi<{items:Student[]}>(`/api/v1/classroom/lab-releases/${releaseId.value}/students`)]);summary.value=s;students.value=l.items}catch(e){error.value=(e as ApiError).message}finally{loading.value=false}}
async function action(name:string, runtimeId?:string){if(!runtimeId)return;busy.value=name;try{await classroomApi(`/api/v1/classroom/runtime/${runtimeId}/${name}`,'teacher',{method:'POST',body:JSON.stringify({reason:'课堂管理操作'})});await load()}catch(e){error.value=(e as ApiError).message}finally{busy.value=''}}
async function releaseAction(name:'extend-all'|'remind-idle'){busy.value=name;try{await classroomApi(`/api/v1/classroom/lab-releases/${releaseId.value}/${name}`,'teacher',{method:'POST',body:JSON.stringify(name==='extend-all'?{minutes:10}:{reason:'课堂批量提醒'})});await load()}catch(e){error.value=(e as ApiError).message}finally{busy.value=''}}
async function openStudent(item:Student){selected.value=item;detail.value=null;try{detail.value=await classroomApi(`/api/v1/classroom/lab-releases/${releaseId.value}/students/${item.student_id}`)}catch(e){error.value=(e as ApiError).message}}
onMounted(load)
</script>
<template><div class="stack"><header class="page-header"><div><h1>实验课堂</h1><p>实时掌握全班实验进度、异常与得分。</p></div><button class="yk-button" @click="load">刷新</button></header>
<div v-if="error" class="pending-panel" role="alert"><b>课堂运行服务待就绪</b><div>{{ error }}</div></div><div v-if="loading" class="card">正在加载课堂数据…</div>
<section v-if="summary" class="grid grid-4"><div class="card kpi">已启动<b>{{summary.started}}</b></div><div class="card kpi">进行中<b>{{summary.running}}</b></div><div class="card kpi">已完成<b>{{summary.completed}}</b></div><div class="card kpi">异常 / 未开始<b>{{summary.failed}} / {{summary.not_started}}</b></div></section>
<section class="card"><div class="toolbar"><input v-model="query" aria-label="搜索学生" placeholder="搜索姓名或学号"><YkSelect v-model="filter" label="状态筛选" :options="[{label:'全部状态',value:'ALL'},{label:'进行中',value:'RUNNING'},{label:'已提交',value:'SUBMITTED'},{label:'异常',value:'FAILED'},{label:'未开始',value:'NOT_STARTED'}]"/><span class="muted">共 {{filtered.length}} 名学生</span><button class="yk-button" :disabled="!!busy" @click="releaseAction('remind-idle')">提醒未活动学生</button><button class="yk-button" :disabled="!!busy" @click="releaseAction('extend-all')">全班延长 10 分钟</button></div>
<div class="scroll"><table class="data-table"><thead><tr><th>学生</th><th>状态</th><th>步骤</th><th>得分</th><th>操作</th></tr></thead><tbody><tr v-for="item in filtered" :key="item.student_id"><td>{{item.student_name}}<div class="muted">{{item.student_no||item.student_id}}</div></td><td><span class="status" :class="{running:item.status==='RUNNING',done:item.status==='SUBMITTED',failed:item.status==='FAILED'}">{{label(item.status)}}</span></td><td>{{item.current_step}} / {{item.total_steps}}</td><td>{{item.raw_score}} / {{item.max_score}}</td><td><button class="yk-button" @click="openStudent(item)">查看</button></td></tr><tr v-if="!filtered.length&&!loading"><td colspan="5" class="muted">暂无符合条件的学生</td></tr></tbody></table></div></section>
<YkDrawer :open="!!selected" :title="selected?.student_name||'学生详情'" @close="selected=null"><YkTabs v-model="tab" :tabs="[{label:'实验步骤',value:'steps'},{label:'协助终端',value:'terminal'},{label:'运行日志',value:'logs'},{label:'课堂处置',value:'actions'}]"/><div v-if="selected" class="stack" style="margin-top:14px"><div v-if="tab==='steps'" class="card"><div>当前步骤：{{selected.current_step}} / {{selected.total_steps}}</div><div class="progress"><span :style="{width:`${selected.total_steps?selected.current_step/selected.total_steps*100:0}%`}"></span></div><p>当前得分：{{selected.raw_score}} / {{selected.max_score}}</p></div><TerminalPanel v-if="tab==='terminal'&&selected.runtime_instance_id" :runtime-id="selected.runtime_instance_id" assist/><div v-if="tab==='terminal'&&!selected.runtime_instance_id" class="pending-panel">该学生尚未创建实验实例。</div><div v-if="tab==='logs'" class="card"><p v-if="!detail?.logs?.length" class="muted">暂无运行日志；完整日志可前往“教学日志”查看。</p><p v-for="(log,index) in detail?.logs||[]" :key="index">{{log.message||log.action}}</p></div><div v-if="tab==='actions'" class="actions"><button class="yk-button" :disabled="!!busy" @click="action('remind',selected.runtime_instance_id)">提醒</button><button class="yk-button" :disabled="!!busy" @click="action('rejudge',selected.runtime_instance_id)">重新判定</button><button class="yk-button" :disabled="!!busy" @click="action('extend',selected.runtime_instance_id)">延长时间</button><button class="yk-button" :disabled="!!busy" @click="action('unlock',selected.runtime_instance_id)">解除锁定</button></div></div></YkDrawer></div></template>
