<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { classroomApi, subscribeClassroomEvents, type ApiError } from '../../app/api'
import YkDrawer from '../../components/common/YkDrawer.vue'
import YkTabs from '../../components/common/YkTabs.vue'
import YkSelect from '../../components/common/YkSelect.vue'
import TerminalPanel from './TerminalPanel.vue'
type Student={student_id:string;student_name:string;student_no?:string;status:string;current_step?:number|null;total_steps?:number|null;raw_score?:number|null;max_score?:number|null;runtime_instance_id?:string;started_at?:string;last_activity_at?:string}
type Summary={started:number;completed:number;running:number;failed:number;not_started:number;data_status?:'READY'|'EMPTY'}
const releaseId=ref(localStorage.getItem('yk-release-id')||'release-1'), summary=ref<Summary|null>(null), students=ref<Student[]>([]), error=ref(''), loading=ref(true), filter=ref('ALL'), query=ref(''), selected=ref<Student|null>(null), detail=ref<any>(null), tab=ref('steps'), busy=ref('')
const liveState=ref<'正在连接'|'实时更新中'|'正在重连'>('正在连接')
let stopEvents:(()=>void)|null=null, refreshTimer:ReturnType<typeof setTimeout>|null=null
const filtered=computed(()=>students.value.filter(x=>(filter.value==='ALL'||x.status===filter.value)&&(`${x.student_name}${x.student_no||''}`).includes(query.value)))
const hasClassroomFacts=computed(()=>!loading.value&&!error.value&&!!summary.value&&students.value.length>0)
const label=(status:string)=>({RUNNING:'进行中',SUBMITTED:'已提交',COMPLETED:'已完成',FAILED:'异常',DESTROYED:'已销毁',CANCELED:'已取消',QUEUED:'排队中',SCHEDULING:'正在调度',STARTING:'启动中',CREATED:'已创建',STOPPING:'正在关闭',NOT_STARTED:'未开始',UNKNOWN:'状态待确认'}[status]||'状态待确认')
const duration=(started?:string)=>{if(!started)return '—';const minutes=Math.max(0,Math.floor((Date.now()-new Date(started).getTime())/60000));return `${Math.floor(minutes/60)} 小时 ${minutes%60} 分`}
const progressText=(item:Student)=>item.current_step==null||item.total_steps==null?'—':`${item.current_step} / ${item.total_steps}`
const scoreText=(item:Student)=>item.raw_score==null||item.max_score==null?'—':`${item.raw_score} / ${item.max_score}`
const progressWidth=(item:Student)=>item.current_step==null||!item.total_steps?0:Math.min(100,item.current_step/item.total_steps*100)
async function load(){loading.value=true;error.value='';summary.value=null;students.value=[];selected.value=null;detail.value=null;try{const [s,l]=await Promise.all([classroomApi<Summary>(`/api/v1/classroom/lab-releases/${releaseId.value}/summary`),classroomApi<{items:Student[]}>(`/api/v1/classroom/lab-releases/${releaseId.value}/students`)]);summary.value=s;students.value=l.items}catch(e){error.value=(e as ApiError).message}finally{loading.value=false}}
async function action(name:string, runtimeId?:string){if(!hasClassroomFacts.value||!runtimeId)return;if(name==='destroy'&&!confirm('销毁后当前实验实例将不可用，确定继续？'))return;if(name==='rebuild'&&!confirm('重建会中断当前终端连接，确定继续？'))return;busy.value=name;const selectedId=selected.value?.student_id;try{await classroomApi(`/api/v1/classroom/runtime/${runtimeId}/${name}`,'teacher',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({reason:'课堂管理操作',...(name==='extend'?{minutes:10}:{})})});await load();selected.value=students.value.find(item=>item.student_id===selectedId)||null}catch(e){error.value=(e as ApiError).message}finally{busy.value=''}}
async function releaseAction(name:'extend-all'|'remind-idle'){if(!hasClassroomFacts.value)return;busy.value=name;try{await classroomApi(`/api/v1/classroom/lab-releases/${releaseId.value}/${name}`,'teacher',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(name==='extend-all'?{minutes:10}:{reason:'课堂批量提醒'})});await load()}catch(e){error.value=(e as ApiError).message}finally{busy.value=''}}
async function openStudent(item:Student){if(!hasClassroomFacts.value)return;selected.value=item;detail.value=null;try{detail.value=await classroomApi(`/api/v1/classroom/lab-releases/${releaseId.value}/students/${item.student_id}`)}catch(e){selected.value=null;detail.value=null;error.value=(e as ApiError).message}}
function refreshFromEvent(){liveState.value='实时更新中';if(refreshTimer)clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>void load(),100)}
onMounted(()=>{void load();stopEvents=subscribeClassroomEvents(releaseId.value,refreshFromEvent,()=>{liveState.value='正在重连'})})
onBeforeUnmount(()=>{stopEvents?.();if(refreshTimer)clearTimeout(refreshTimer)})
</script>
<template><div class="stack"><header class="page-header"><div><h1>实验课堂</h1><p>实时掌握全班实验进度、异常与得分。<span class="muted" data-testid="live-state">{{liveState}}</span></p></div><button class="yk-button" @click="load">刷新</button></header>
  <div v-if="error" class="pending-panel" role="alert"><b>无法读取课堂运行事实</b><div>{{ error }}</div></div><div v-if="loading" class="card">正在加载课堂数据…</div>
  <section v-if="hasClassroomFacts" class="grid" style="grid-template-columns:repeat(auto-fit,minmax(150px,1fr))"><div class="card kpi">已启动<b>{{summary?.started}}</b></div><div class="card kpi">已完成<b>{{summary?.completed}}</b></div><div class="card kpi">进行中<b>{{summary?.running}}</b></div><div class="card kpi">异常 / 卡住<b>{{summary?.failed}}</b></div><div class="card kpi">未启动<b>{{summary?.not_started}}</b></div></section>
  <section v-else-if="!loading&&!error" class="card muted">当前班级没有可展示的课堂运行事实。</section>
  <section v-if="hasClassroomFacts" class="card"><div class="toolbar"><input v-model="query" aria-label="搜索学生" placeholder="搜索姓名或学号"><YkSelect v-model="filter" label="状态筛选" :options="[{label:'全部状态',value:'ALL'},{label:'进行中',value:'RUNNING'},{label:'已提交',value:'SUBMITTED'},{label:'异常',value:'FAILED'},{label:'未开始',value:'NOT_STARTED'}]"/><span class="muted">共 {{filtered.length}} 名学生</span><button class="yk-button" :disabled="!hasClassroomFacts||!!busy" @click="releaseAction('remind-idle')">提醒未活动学生</button><button class="yk-button" :disabled="!hasClassroomFacts||!!busy" @click="releaseAction('extend-all')">全班延长 10 分钟</button></div>
  <div class="scroll"><table class="data-table"><thead><tr><th>学生</th><th>状态</th><th>当前步骤 / 进度</th><th>得分</th><th>运行时长</th><th>实例</th><th>最后活动</th><th>操作</th></tr></thead><tbody><tr v-for="item in filtered" :key="item.student_id"><td>{{item.student_name}}<div class="muted">{{item.student_no||item.student_id}}</div></td><td><span class="status" :class="{running:item.status==='RUNNING',done:item.status==='SUBMITTED',failed:item.status==='FAILED'}">{{label(item.status)}}</span></td><td>{{progressText(item)}}<div class="progress"><span :style="{width:`${progressWidth(item)}%`}"></span></div></td><td>{{scoreText(item)}}</td><td>{{duration(item.started_at)}}</td><td>{{item.runtime_instance_id||'尚未创建'}}</td><td>{{item.last_activity_at||'—'}}</td><td><button class="yk-button" @click="openStudent(item)">查看</button></td></tr><tr v-if="!filtered.length"><td colspan="8" class="muted">暂无符合条件的学生</td></tr></tbody></table></div></section>
  <YkDrawer :open="!!selected" :title="selected?.student_name||'学生详情'" @close="selected=null"><YkTabs v-model="tab" :tabs="[{label:'实验步骤',value:'steps'},{label:'协助终端',value:'terminal'},{label:'运行日志',value:'logs'},{label:'课堂处置',value:'actions'}]"/><div v-if="selected" class="stack" style="margin-top:14px"><div v-if="tab==='steps'" class="card"><div>当前步骤：{{progressText(selected)}}</div><div class="progress"><span :style="{width:`${progressWidth(selected)}%`}"></span></div><p>当前得分：{{scoreText(selected)}}</p></div><TerminalPanel v-if="tab==='terminal'&&selected.runtime_instance_id" :runtime-id="selected.runtime_instance_id" assist/><div v-if="tab==='terminal'&&!selected.runtime_instance_id" class="pending-panel">该学生尚未创建实验实例。</div><div v-if="tab==='logs'" class="card"><p v-if="!detail?.logs?.length" class="muted">暂无运行日志；完整日志可前往“教学日志”查看。</p><p v-for="(log,index) in detail?.logs||[]" :key="index">{{log.message||log.action}}</p></div><div v-if="tab==='actions'" class="actions"><button class="yk-button" :disabled="!hasClassroomFacts||!!busy||!selected.runtime_instance_id" @click="action('remind',selected.runtime_instance_id)">提醒</button><button class="yk-button" :disabled="!hasClassroomFacts||!!busy||!selected.runtime_instance_id" @click="action('rejudge',selected.runtime_instance_id)">重新判定</button><button class="yk-button" :disabled="!hasClassroomFacts||!!busy||!selected.runtime_instance_id" @click="action('extend',selected.runtime_instance_id)">延长 10 分钟</button><button class="yk-button" :disabled="!hasClassroomFacts||!!busy||!selected.runtime_instance_id" @click="action('unlock',selected.runtime_instance_id)">解除锁定</button><button class="yk-button" :disabled="!hasClassroomFacts||!!busy||!selected.runtime_instance_id" @click="action('rebuild',selected.runtime_instance_id)">重建实例</button><button class="yk-button danger" :disabled="!hasClassroomFacts||!!busy||!selected.runtime_instance_id" @click="action('destroy',selected.runtime_instance_id)">销毁实例</button></div></div></YkDrawer></div></template>
