<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { classroomApi, type ApiError } from '../../app/api'
import YkTabs from '../../components/common/YkTabs.vue'
type Item={artifact_id?:string;name?:string;student_id?:string;occurred_at?:string;action?:string;size_bytes?:number}
const tab=ref('audit'), items=ref<Item[]>([]), error=ref(''), history=ref<any[]>([]), title=ref('网络流量分析'), instruction=ref('下载日志并定位异常连接'), targets=ref('student-a'), count=ref(1), dueAt=ref(''), message=ref('')
async function load(){error.value='';try{const path=tab.value==='audit'?'/api/v1/teaching-logs/audit':'/api/v1/teaching-logs/traffic';items.value=(await classroomApi<{items:Item[]}>(path)).items;history.value=(await classroomApi<{items:any[]}>('/api/v1/teaching-logs/distributions')).items}catch(e){error.value=(e as ApiError).message}}
async function download(id?:string){if(!id||tab.value!=='traffic')return;try{const r=await classroomApi<{download_url:string}>(`/api/v1/teaching-logs/traffic/${id}/download`);window.open(r.download_url,'_blank','noopener')}catch(e){error.value=(e as ApiError).message}}
async function distribute(){message.value='';error.value='';try{await classroomApi('/api/v1/teaching-logs/distributions','teacher',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({course_id:localStorage.getItem('yk-course-id')||'course-a',class_id:localStorage.getItem('yk-class-id')||'class-a',lab_release_id:localStorage.getItem('yk-release-id')||'release-1',distribution_type:tab.value==='audit'?'AUDIT':'TRAFFIC',source_filter:{},requested_count:count.value,target_student_ids:targets.value.split(',').map(x=>x.trim()).filter(Boolean),title:title.value,instruction:instruction.value,due_at:dueAt.value||null})});message.value='日志任务已分发';await load()}catch(e){error.value=(e as ApiError).message}}
onMounted(load)
</script>
<template><div class="stack"><header class="page-header"><div><h1>教学日志</h1><p>查阅审计与流量日志，并向本班学生分发训练材料。</p></div></header><YkTabs v-model="tab" :tabs="[{label:'审计日志',value:'audit'},{label:'流量日志',value:'traffic'}]" @update:model-value="load"/><div v-if="error" class="pending-panel">{{error}}</div><section class="grid grid-2"><div class="card"><h3>日志清单</h3><table class="data-table"><thead><tr><th>日志</th><th>学生</th><th>操作</th></tr></thead><tbody><tr v-for="(item,index) in items" :key="item.artifact_id||index"><td>{{item.name||item.action||'审计事件'}}</td><td>{{item.student_id||'系统'}}</td><td><button v-if="item.artifact_id&&tab==='traffic'" class="yk-button" @click="download(item.artifact_id)">下载</button><span v-else class="muted">仅供查阅</span></td></tr><tr v-if="!items.length"><td colspan="3" class="muted">暂无日志，或数据源待接入</td></tr></tbody></table></div><form class="card form-grid" @submit.prevent="distribute"><h3>分发日志任务</h3><label>任务名称<input v-model="title" required></label><label>任务要求<textarea v-model="instruction" required></textarea></label><label>目标学生编号（逗号分隔）<input v-model="targets" required></label><label>日志数量<input v-model.number="count" type="number" min="1" max="1000"></label><label>截止时间（可选）<input v-model="dueAt" type="datetime-local"></label><button class="yk-button primary">确认分发</button><p v-if="message" class="status done">{{message}}</p></form></section><section class="card"><h3>分发记录</h3><p v-if="!history.length" class="muted">暂无分发记录</p><table v-else class="data-table"><thead><tr><th>任务名称</th><th>类型</th><th>状态</th><th>创建时间</th></tr></thead><tbody><tr v-for="item in history" :key="item.distribution_id"><td>{{item.title}}</td><td>{{item.distribution_type==='TRAFFIC'?'流量日志':'审计日志'}}</td><td>{{item.status}}</td><td>{{item.created_at}}</td></tr></tbody></table></section></div></template>
