<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { classroomApi, type ApiError } from '../../app/api'
import YkSelect from '../../components/common/YkSelect.vue'
type Row={student_id:string;student_name:string;status:string;runtime_instance_id?:string;started_at?:string;last_activity_at?:string}
const release=localStorage.getItem('yk-release-id')||'release-1', rows=ref<Row[]>([]), error=ref(''), filter=ref('ALL'), query=ref(''), busy=ref('')
const visible=computed(()=>rows.value.filter(x=>(filter.value==='ALL'||x.status===filter.value)&&(`${x.student_name}${x.student_id}${x.runtime_instance_id||''}`).includes(query.value.trim())))
const counts=computed(()=>({started:rows.value.filter(x=>x.status!=='NOT_STARTED').length,waiting:rows.value.filter(x=>x.status==='NOT_STARTED').length,running:rows.value.filter(x=>x.status==='RUNNING').length,destroyed:rows.value.filter(x=>x.status==='DESTROYED').length,failed:rows.value.filter(x=>x.status==='FAILED').length}))
const statusLabel=(status:string)=>({RUNNING:'运行中',SUBMITTED:'已提交',COMPLETED:'已完成',FAILED:'异常',DESTROYED:'已销毁',QUEUED:'排队中',STARTING:'启动中',NOT_STARTED:'未启动'}[status]||'状态待确认')
async function load(){error.value='';try{rows.value=(await classroomApi<{items:Row[]}>(`/api/v1/classroom/lab-releases/${release}/students`)).items}catch(e){error.value=(e as ApiError).message}}
async function operate(row:Row,action:'rebuild'|'destroy'){if(!row.runtime_instance_id)return;if(!confirm(action==='destroy'?'销毁后当前实例将不可用，确定继续？':'重建会中断当前终端连接，确定继续？'))return;busy.value=row.runtime_instance_id;try{await classroomApi(`/api/v1/classroom/runtime/${row.runtime_instance_id}/${action}`,'teacher',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({reason:'教师实例管理'})});await load()}catch(e){error.value=(e as ApiError).message}finally{busy.value=''}}
onMounted(load)
</script>
<template><div class="stack"><header class="page-header"><div><h1>实验实例</h1><p>查看实例状态并执行审计留痕的重建或销毁操作。</p></div><button class="yk-button" @click="load">刷新</button></header><div v-if="error" class="pending-panel">运行管理服务待就绪：{{error}}</div><section class="grid grid-4"><div class="card kpi">已启动<b>{{counts.started}}</b></div><div class="card kpi">等待启动<b>{{counts.waiting}}</b></div><div class="card kpi">运行中<b>{{counts.running}}</b></div><div class="card kpi">销毁 / 异常<b>{{counts.destroyed}} / {{counts.failed}}</b></div></section><section class="card"><div class="toolbar"><input v-model="query" aria-label="搜索学生或实例" placeholder="搜索学生或实例"><YkSelect v-model="filter" label="状态筛选" :options="[{label:'全部状态',value:'ALL'},{label:'运行中',value:'RUNNING'},{label:'异常',value:'FAILED'},{label:'已提交',value:'SUBMITTED'},{label:'已销毁',value:'DESTROYED'},{label:'未启动',value:'NOT_STARTED'}]"/><span class="muted">共 {{visible.length}} 条记录</span></div><div class="scroll"><table class="data-table"><thead><tr><th>学生</th><th>实例编号</th><th>状态</th><th>启动时间</th><th>最后活动</th><th>操作</th></tr></thead><tbody><tr v-for="row in visible" :key="row.student_id"><td>{{row.student_name}}</td><td>{{row.runtime_instance_id||'尚未创建'}}</td><td><span class="status" :class="{running:row.status==='RUNNING',done:row.status==='SUBMITTED',failed:row.status==='FAILED'}">{{statusLabel(row.status)}}</span></td><td>{{row.started_at||'—'}}</td><td>{{row.last_activity_at||'—'}}</td><td class="actions"><button class="yk-button" :disabled="!row.runtime_instance_id||busy===row.runtime_instance_id" @click="operate(row,'rebuild')">重建</button><button class="yk-button danger" :disabled="!row.runtime_instance_id||busy===row.runtime_instance_id" @click="operate(row,'destroy')">销毁</button></td></tr><tr v-if="!visible.length"><td colspan="6" class="muted">暂无实例数据</td></tr></tbody></table></div></section></div></template>
