"""create grading analytics archive and audit domain

Revision ID: 20260921_0002
Revises: 20260921_0001
"""
from alembic import op
import sqlalchemy as sa

revision = "20260921_0002"
down_revision = "20260921_0001"
branch_labels = ("grading_analytics",)
depends_on = None


def upgrade() -> None:
    op.create_table("grading_policy", sa.Column("grading_policy_id",sa.String(36),primary_key=True),sa.Column("course_id",sa.String(36),nullable=False),sa.Column("version_no",sa.Integer(),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("effective_at",sa.DateTime(),nullable=False),sa.Column("created_by",sa.String(36),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("course_id","version_no",name="uq_grading_policy_version"))
    op.create_index("ix_grading_policy_course_id","grading_policy",["course_id"])
    op.create_table("grading_policy_item",sa.Column("grading_policy_item_id",sa.String(36),primary_key=True),sa.Column("grading_policy_id",sa.String(36),sa.ForeignKey("grading_policy.grading_policy_id",ondelete="RESTRICT"),nullable=False),sa.Column("component",sa.String(24),nullable=False),sa.Column("weight_percent",sa.Numeric(5,2),nullable=False),sa.UniqueConstraint("grading_policy_id","component",name="uq_policy_component"))
    op.create_index("ix_grading_policy_item_grading_policy_id","grading_policy_item",["grading_policy_id"])
    op.create_table("grade_event",sa.Column("grade_event_id",sa.String(36),primary_key=True),sa.Column("course_id",sa.String(36),nullable=False),sa.Column("class_id",sa.String(36),nullable=False),sa.Column("lesson_id",sa.String(36)),sa.Column("student_id",sa.String(36),nullable=False),sa.Column("source_type",sa.String(32),nullable=False),sa.Column("source_id",sa.String(36),nullable=False),sa.Column("raw_score",sa.Numeric(8,2),nullable=False),sa.Column("max_score",sa.Numeric(8,2),nullable=False),sa.Column("normalized_score",sa.Numeric(6,2),nullable=False),sa.Column("occurred_at",sa.DateTime(),nullable=False),sa.Column("event_id",sa.String(36),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("payload_json",sa.JSON(),nullable=False),sa.UniqueConstraint("event_id",name="uq_grade_event_source_event"))
    op.create_index("ix_grade_event_scope","grade_event",["course_id","class_id","student_id","source_type"])
    op.create_table("gradebook",sa.Column("gradebook_id",sa.String(36),primary_key=True),sa.Column("course_id",sa.String(36),nullable=False),sa.Column("class_id",sa.String(36),nullable=False),sa.Column("policy_version",sa.Integer(),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("calculated_at",sa.DateTime(),nullable=False),sa.Column("posted_at",sa.DateTime()),sa.Column("locked_at",sa.DateTime()),sa.UniqueConstraint("course_id","class_id","policy_version",name="uq_gradebook_policy"))
    op.create_index("ix_gradebook_course_id","gradebook",["course_id"]);op.create_index("ix_gradebook_class_id","gradebook",["class_id"])
    op.create_table("gradebook_item",sa.Column("gradebook_item_id",sa.String(36),primary_key=True),sa.Column("gradebook_id",sa.String(36),sa.ForeignKey("gradebook.gradebook_id",ondelete="CASCADE"),nullable=False),sa.Column("student_id",sa.String(36),nullable=False),sa.Column("component",sa.String(24),nullable=False),sa.Column("component_score",sa.Numeric(6,2),nullable=False),sa.Column("weight_percent",sa.Numeric(5,2),nullable=False),sa.Column("weighted_score",sa.Numeric(6,2),nullable=False),sa.UniqueConstraint("gradebook_id","student_id","component",name="uq_gradebook_student_component"))
    op.create_index("ix_gradebook_item_gradebook_id","gradebook_item",["gradebook_id"]);op.create_index("ix_gradebook_item_student_id","gradebook_item",["student_id"])
    op.create_table("student_course_score",sa.Column("student_course_score_id",sa.String(36),primary_key=True),sa.Column("gradebook_id",sa.String(36),sa.ForeignKey("gradebook.gradebook_id",ondelete="CASCADE"),nullable=False),sa.Column("course_id",sa.String(36),nullable=False),sa.Column("class_id",sa.String(36),nullable=False),sa.Column("student_id",sa.String(36),nullable=False),sa.Column("total_score",sa.Numeric(6,2),nullable=False),sa.Column("completeness",sa.String(16),nullable=False),sa.UniqueConstraint("gradebook_id","student_id",name="uq_student_course_score"))
    for col in ["gradebook_id","course_id","class_id","student_id"]: op.create_index(f"ix_student_course_score_{col}","student_course_score",[col])
    op.create_table("analytics_course_summary",sa.Column("analytics_course_summary_id",sa.String(36),primary_key=True),sa.Column("gradebook_id",sa.String(36),sa.ForeignKey("gradebook.gradebook_id",ondelete="CASCADE"),nullable=False,unique=True),sa.Column("course_id",sa.String(36),nullable=False),sa.Column("class_id",sa.String(36),nullable=False),sa.Column("summary_json",sa.JSON(),nullable=False),sa.Column("calculated_at",sa.DateTime(),nullable=False))
    op.create_index("ix_analytics_course_summary_course_id","analytics_course_summary",["course_id"]);op.create_index("ix_analytics_course_summary_class_id","analytics_course_summary",["class_id"])
    op.create_table("analytics_section_summary",sa.Column("analytics_section_summary_id",sa.String(36),primary_key=True),sa.Column("gradebook_id",sa.String(36),sa.ForeignKey("gradebook.gradebook_id",ondelete="CASCADE"),nullable=False),sa.Column("lesson_id",sa.String(36),nullable=False),sa.Column("summary_json",sa.JSON(),nullable=False),sa.UniqueConstraint("gradebook_id","lesson_id",name="uq_analytics_section"))
    op.create_index("ix_analytics_section_summary_gradebook_id","analytics_section_summary",["gradebook_id"]);op.create_index("ix_analytics_section_summary_lesson_id","analytics_section_summary",["lesson_id"])
    op.create_table("analytics_student_lab_summary",sa.Column("analytics_student_lab_summary_id",sa.String(36),primary_key=True),sa.Column("gradebook_id",sa.String(36),sa.ForeignKey("gradebook.gradebook_id",ondelete="CASCADE"),nullable=False),sa.Column("student_id",sa.String(36),nullable=False),sa.Column("sum_lab_score",sa.Numeric(10,2),nullable=False),sa.Column("submitted_count",sa.Integer(),nullable=False),sa.Column("unsubmitted_count",sa.Integer(),nullable=False),sa.UniqueConstraint("gradebook_id","student_id",name="uq_analytics_student_lab"))
    op.create_index("ix_analytics_student_lab_summary_gradebook_id","analytics_student_lab_summary",["gradebook_id"]);op.create_index("ix_analytics_student_lab_summary_student_id","analytics_student_lab_summary",["student_id"])
    op.create_table("analytics_lab_summary",sa.Column("analytics_lab_summary_id",sa.String(36),primary_key=True),sa.Column("gradebook_id",sa.String(36),sa.ForeignKey("gradebook.gradebook_id",ondelete="CASCADE"),nullable=False),sa.Column("lab_release_id",sa.String(36),nullable=False),sa.Column("max_score",sa.Numeric(8,2),nullable=False),sa.Column("submitted_students",sa.Integer(),nullable=False),sa.Column("unsubmitted_students",sa.Integer(),nullable=False),sa.Column("avg_score",sa.Numeric(6,2),nullable=False),sa.UniqueConstraint("gradebook_id","lab_release_id",name="uq_analytics_lab"))
    op.create_index("ix_analytics_lab_summary_gradebook_id","analytics_lab_summary",["gradebook_id"]);op.create_index("ix_analytics_lab_summary_lab_release_id","analytics_lab_summary",["lab_release_id"])
    op.create_table("student_risk_flag",sa.Column("student_risk_flag_id",sa.String(36),primary_key=True),sa.Column("gradebook_id",sa.String(36),sa.ForeignKey("gradebook.gradebook_id",ondelete="CASCADE"),nullable=False),sa.Column("course_id",sa.String(36),nullable=False),sa.Column("class_id",sa.String(36),nullable=False),sa.Column("student_id",sa.String(36),nullable=False),sa.Column("risk_type",sa.String(32),nullable=False),sa.Column("evidence_json",sa.JSON(),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False))
    op.create_index("ix_student_risk_flag_gradebook_id","student_risk_flag",["gradebook_id"]);op.create_index("ix_risk_scope","student_risk_flag",["course_id","class_id","student_id","status"])
    op.create_table("course_archive",sa.Column("course_archive_id",sa.String(36),primary_key=True),sa.Column("course_id",sa.String(36),nullable=False),sa.Column("class_id",sa.String(36),nullable=False),sa.Column("gradebook_id",sa.String(36)),sa.Column("status",sa.String(16),nullable=False),sa.Column("precheck_json",sa.JSON(),nullable=False),sa.Column("manifest_json",sa.JSON()),sa.Column("created_by",sa.String(36),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("archived_at",sa.DateTime()),sa.UniqueConstraint("course_id","class_id",name="uq_course_archive"))
    op.create_index("ix_course_archive_course_id","course_archive",["course_id"]);op.create_index("ix_course_archive_class_id","course_archive",["class_id"])
    op.create_table("course_archive_artifact",sa.Column("course_archive_artifact_id",sa.String(36),primary_key=True),sa.Column("course_archive_id",sa.String(36),sa.ForeignKey("course_archive.course_archive_id",ondelete="RESTRICT"),nullable=False),sa.Column("artifact_type",sa.String(32),nullable=False),sa.Column("file_id",sa.String(36)),sa.Column("evidence_ref",sa.String(255),nullable=False),sa.Column("sha256",sa.String(64)))
    op.create_index("ix_course_archive_artifact_course_archive_id","course_archive_artifact",["course_archive_id"])
    op.create_table("audit_event",sa.Column("audit_event_id",sa.String(36),primary_key=True),sa.Column("actor_user_id",sa.String(36),nullable=False),sa.Column("actor_role",sa.String(16),nullable=False),sa.Column("action",sa.String(64),nullable=False),sa.Column("resource_type",sa.String(64),nullable=False),sa.Column("resource_id",sa.String(36),nullable=False),sa.Column("course_id",sa.String(36)),sa.Column("class_id",sa.String(36)),sa.Column("student_id",sa.String(36)),sa.Column("request_id",sa.String(64),nullable=False),sa.Column("ip",sa.String(64),nullable=False),sa.Column("result",sa.String(16),nullable=False),sa.Column("reason",sa.Text()),sa.Column("occurred_at",sa.DateTime(),nullable=False),sa.Column("details_json",sa.JSON(),nullable=False))
    op.create_index("ix_audit_scope","audit_event",["course_id","class_id","student_id","occurred_at"]);op.create_index("ix_audit_action","audit_event",["action","result"])


def downgrade() -> None:
    for table in ["audit_event","course_archive_artifact","course_archive","student_risk_flag","analytics_lab_summary","analytics_student_lab_summary","analytics_section_summary","analytics_course_summary","student_course_score","gradebook_item","gradebook","grade_event","grading_policy_item","grading_policy"]:
        op.drop_table(table)
