"""add lab classroom orchestration

Revision ID: aa9dbaa36663
Revises: 20260921_0001
"""
from alembic import op
import sqlalchemy as sa

revision = 'aa9dbaa36663'
down_revision = '20260921_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_consumed_event',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('event_type', 'idempotency_key', name='uq_classroom_event_idempotency')
    )
    op.create_index(op.f('ix_classroom_consumed_event_aggregate_id'), 'classroom_consumed_event', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_classroom_consumed_event_event_type'), 'classroom_consumed_event', ['event_type'], unique=False)
    op.create_table('classroom_runtime_event',
    sa.Column('event_sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('lab_release_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_sequence'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_classroom_runtime_event_lab_release_id'), 'classroom_runtime_event', ['lab_release_id'], unique=False)
    op.create_index(op.f('ix_classroom_runtime_event_student_id'), 'classroom_runtime_event', ['student_id'], unique=False)
    op.create_table('classroom_runtime_projection',
    sa.Column('projection_id', sa.String(length=36), nullable=False),
    sa.Column('lab_release_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('runtime_instance_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('raw_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('projection_id'),
    sa.UniqueConstraint('lab_release_id', 'student_id', name='uq_classroom_release_student')
    )
    op.create_index(op.f('ix_classroom_runtime_projection_class_id'), 'classroom_runtime_projection', ['class_id'], unique=False)
    op.create_index(op.f('ix_classroom_runtime_projection_course_id'), 'classroom_runtime_projection', ['course_id'], unique=False)
    op.create_index(op.f('ix_classroom_runtime_projection_lab_release_id'), 'classroom_runtime_projection', ['lab_release_id'], unique=False)
    op.create_index(op.f('ix_classroom_runtime_projection_runtime_instance_id'), 'classroom_runtime_projection', ['runtime_instance_id'], unique=False)
    op.create_index(op.f('ix_classroom_runtime_projection_student_id'), 'classroom_runtime_projection', ['student_id'], unique=False)
    op.create_index('ix_classroom_scope_status', 'classroom_runtime_projection', ['class_id', 'lab_release_id', 'status'], unique=False)
    op.create_table('teaching_log_distribution_task',
    sa.Column('distribution_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('lab_release_id', sa.String(length=36), nullable=False),
    sa.Column('distribution_type', sa.String(length=24), nullable=False),
    sa.Column('source_filter_json', sa.JSON(), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('distribution_id'),
    sa.UniqueConstraint('class_id', 'idempotency_key', name='uq_log_distribution_idempotency')
    )
    op.create_index(op.f('ix_teaching_log_distribution_task_class_id'), 'teaching_log_distribution_task', ['class_id'], unique=False)
    op.create_index(op.f('ix_teaching_log_distribution_task_course_id'), 'teaching_log_distribution_task', ['course_id'], unique=False)
    op.create_index(op.f('ix_teaching_log_distribution_task_lab_release_id'), 'teaching_log_distribution_task', ['lab_release_id'], unique=False)
    op.create_table('student_log_assignment',
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('distribution_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['distribution_id'], ['teaching_log_distribution_task.distribution_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id'),
    sa.UniqueConstraint('distribution_id', 'student_id', name='uq_distribution_student')
    )
    op.create_index(op.f('ix_student_log_assignment_class_id'), 'student_log_assignment', ['class_id'], unique=False)
    op.create_index(op.f('ix_student_log_assignment_distribution_id'), 'student_log_assignment', ['distribution_id'], unique=False)
    op.create_index(op.f('ix_student_log_assignment_student_id'), 'student_log_assignment', ['student_id'], unique=False)
    op.create_table('teaching_log_distribution_item',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('distribution_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('source_system', sa.String(length=16), nullable=False),
    sa.Column('source_student_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_type', sa.String(length=24), nullable=False),
    sa.Column('artifact_meta_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['distribution_id'], ['teaching_log_distribution_task.distribution_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('distribution_id', 'artifact_id', name='uq_distribution_artifact')
    )
    op.create_index(op.f('ix_teaching_log_distribution_item_artifact_id'), 'teaching_log_distribution_item', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_teaching_log_distribution_item_distribution_id'), 'teaching_log_distribution_item', ['distribution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teaching_log_distribution_item_distribution_id'), table_name='teaching_log_distribution_item')
    op.drop_index(op.f('ix_teaching_log_distribution_item_artifact_id'), table_name='teaching_log_distribution_item')
    op.drop_table('teaching_log_distribution_item')
    op.drop_index(op.f('ix_student_log_assignment_student_id'), table_name='student_log_assignment')
    op.drop_index(op.f('ix_student_log_assignment_distribution_id'), table_name='student_log_assignment')
    op.drop_index(op.f('ix_student_log_assignment_class_id'), table_name='student_log_assignment')
    op.drop_table('student_log_assignment')
    op.drop_index(op.f('ix_teaching_log_distribution_task_lab_release_id'), table_name='teaching_log_distribution_task')
    op.drop_index(op.f('ix_teaching_log_distribution_task_course_id'), table_name='teaching_log_distribution_task')
    op.drop_index(op.f('ix_teaching_log_distribution_task_class_id'), table_name='teaching_log_distribution_task')
    op.drop_table('teaching_log_distribution_task')
    op.drop_index('ix_classroom_scope_status', table_name='classroom_runtime_projection')
    op.drop_index(op.f('ix_classroom_runtime_projection_student_id'), table_name='classroom_runtime_projection')
    op.drop_index(op.f('ix_classroom_runtime_projection_runtime_instance_id'), table_name='classroom_runtime_projection')
    op.drop_index(op.f('ix_classroom_runtime_projection_lab_release_id'), table_name='classroom_runtime_projection')
    op.drop_index(op.f('ix_classroom_runtime_projection_course_id'), table_name='classroom_runtime_projection')
    op.drop_index(op.f('ix_classroom_runtime_projection_class_id'), table_name='classroom_runtime_projection')
    op.drop_table('classroom_runtime_projection')
    op.drop_index(op.f('ix_classroom_runtime_event_student_id'), table_name='classroom_runtime_event')
    op.drop_index(op.f('ix_classroom_runtime_event_lab_release_id'), table_name='classroom_runtime_event')
    op.drop_table('classroom_runtime_event')
    op.drop_index(op.f('ix_classroom_consumed_event_event_type'), table_name='classroom_consumed_event')
    op.drop_index(op.f('ix_classroom_consumed_event_aggregate_id'), table_name='classroom_consumed_event')
    op.drop_table('classroom_consumed_event')
    # ### end Alembic commands ###
