"""add teaching core domain

Revision ID: f4e75e84c503
Revises: 20260921_0001
"""
from alembic import op
import sqlalchemy as sa

revision = 'f4e75e84c503'
down_revision = '20260921_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('term', sa.String(length=64), nullable=False),
    sa.Column('owner_teacher_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_index(op.f('ix_class_owner_teacher_id'), 'class', ['owner_teacher_id'], unique=False)
    op.create_table('course',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('term', sa.String(length=64), nullable=False),
    sa.Column('owner_teacher_id', sa.String(length=36), nullable=False),
    sa.Column('major', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_index(op.f('ix_course_owner_teacher_id'), 'course', ['owner_teacher_id'], unique=False)
    op.create_table('class_course',
    sa.Column('class_course_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_course_id'),
    sa.UniqueConstraint('class_id', 'course_id', name='uq_class_course')
    )
    op.create_index(op.f('ix_class_course_class_id'), 'class_course', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_course_course_id'), 'class_course', ['course_id'], unique=False)
    op.create_table('class_membership',
    sa.Column('class_membership_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('student_number', sa.String(length=64), nullable=False),
    sa.Column('student_name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_membership_id'),
    sa.UniqueConstraint('class_id', 'student_id', name='uq_membership_class_student'),
    sa.UniqueConstraint('class_id', 'student_number', name='uq_membership_class_number')
    )
    op.create_index(op.f('ix_class_membership_class_id'), 'class_membership', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_membership_student_id'), 'class_membership', ['student_id'], unique=False)
    op.create_table('course_chapter',
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chapter_id'),
    sa.UniqueConstraint('course_id', 'sequence', name='uq_chapter_course_sequence')
    )
    op.create_index(op.f('ix_course_chapter_course_id'), 'course_chapter', ['course_id'], unique=False)
    op.create_table('teaching_import_job',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('error_rows_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('class_id', 'idempotency_key', name='uq_import_class_idempotency')
    )
    op.create_index(op.f('ix_teaching_import_job_class_id'), 'teaching_import_job', ['class_id'], unique=False)
    op.create_table('teaching_teacher_assignment',
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id'),
    sa.UniqueConstraint('teacher_id', 'class_id', 'course_id', name='uq_teacher_class_course')
    )
    op.create_index(op.f('ix_teaching_teacher_assignment_class_id'), 'teaching_teacher_assignment', ['class_id'], unique=False)
    op.create_index(op.f('ix_teaching_teacher_assignment_course_id'), 'teaching_teacher_assignment', ['course_id'], unique=False)
    op.create_index(op.f('ix_teaching_teacher_assignment_teacher_id'), 'teaching_teacher_assignment', ['teacher_id'], unique=False)
    op.create_table('course_lesson',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('lesson_type', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['course_chapter.chapter_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id'),
    sa.UniqueConstraint('chapter_id', 'sequence', name='uq_lesson_chapter_sequence')
    )
    op.create_index(op.f('ix_course_lesson_chapter_id'), 'course_lesson', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_course_lesson_course_id'), 'course_lesson', ['course_id'], unique=False)
    op.create_table('assignment',
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('random_order', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lesson.lesson_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_assignment_class_id'), 'assignment', ['class_id'], unique=False)
    op.create_index(op.f('ix_assignment_course_id'), 'assignment', ['course_id'], unique=False)
    op.create_table('attendance_task',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('sign_token_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lesson.lesson_id'], ),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('sign_token_hash')
    )
    op.create_index('ix_attendance_scope_status', 'attendance_task', ['course_id', 'class_id', 'status'], unique=False)
    op.create_index(op.f('ix_attendance_task_class_id'), 'attendance_task', ['class_id'], unique=False)
    op.create_index(op.f('ix_attendance_task_course_id'), 'attendance_task', ['course_id'], unique=False)
    op.create_index(op.f('ix_attendance_task_lesson_id'), 'attendance_task', ['lesson_id'], unique=False)
    op.create_table('poll',
    sa.Column('poll_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('poll_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lesson.lesson_id'], ),
    sa.PrimaryKeyConstraint('poll_id')
    )
    op.create_index(op.f('ix_poll_class_id'), 'poll', ['class_id'], unique=False)
    op.create_index(op.f('ix_poll_course_id'), 'poll', ['course_id'], unique=False)
    op.create_table('quiz',
    sa.Column('quiz_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('random_order', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lesson.lesson_id'], ),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_index(op.f('ix_quiz_class_id'), 'quiz', ['class_id'], unique=False)
    op.create_index(op.f('ix_quiz_course_id'), 'quiz', ['course_id'], unique=False)
    op.create_table('assignment_question_ref',
    sa.Column('ref_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('question_version', sa.String(length=40), nullable=False),
    sa.Column('question_snapshot', sa.JSON(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.assignment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ref_id')
    )
    op.create_index(op.f('ix_assignment_question_ref_assignment_id'), 'assignment_question_ref', ['assignment_id'], unique=False)
    op.create_table('assignment_submission',
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('answers_json', sa.JSON(), nullable=False),
    sa.Column('raw_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.assignment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id'),
    sa.UniqueConstraint('assignment_id', 'student_id', name='uq_assignment_student')
    )
    op.create_index(op.f('ix_assignment_submission_assignment_id'), 'assignment_submission', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_submission_student_id'), 'assignment_submission', ['student_id'], unique=False)
    op.create_table('attendance_record',
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=False),
    sa.Column('result', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['attendance_task.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('task_id', 'student_id', name='uq_attendance_task_student')
    )
    op.create_index(op.f('ix_attendance_record_student_id'), 'attendance_record', ['student_id'], unique=False)
    op.create_index(op.f('ix_attendance_record_task_id'), 'attendance_record', ['task_id'], unique=False)
    op.create_table('poll_option',
    sa.Column('option_id', sa.String(length=36), nullable=False),
    sa.Column('poll_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.poll_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('option_id')
    )
    op.create_index(op.f('ix_poll_option_poll_id'), 'poll_option', ['poll_id'], unique=False)
    op.create_table('quiz_attempt',
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('quiz_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('raw_score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id'),
    sa.UniqueConstraint('quiz_id', 'student_id', name='uq_quiz_student')
    )
    op.create_index(op.f('ix_quiz_attempt_quiz_id'), 'quiz_attempt', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempt_student_id'), 'quiz_attempt', ['student_id'], unique=False)
    op.create_table('quiz_question_ref',
    sa.Column('ref_id', sa.String(length=36), nullable=False),
    sa.Column('quiz_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('question_version', sa.String(length=40), nullable=False),
    sa.Column('question_snapshot', sa.JSON(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ref_id')
    )
    op.create_index(op.f('ix_quiz_question_ref_quiz_id'), 'quiz_question_ref', ['quiz_id'], unique=False)
    op.create_table('poll_answer',
    sa.Column('answer_id', sa.String(length=36), nullable=False),
    sa.Column('poll_id', sa.String(length=36), nullable=False),
    sa.Column('option_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['poll_option.option_id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.poll_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_id'),
    sa.UniqueConstraint('poll_id', 'student_id', name='uq_poll_student')
    )
    op.create_index(op.f('ix_poll_answer_poll_id'), 'poll_answer', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_answer_student_id'), 'poll_answer', ['student_id'], unique=False)
    op.create_table('quiz_answer',
    sa.Column('answer_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('question_ref_id', sa.String(length=36), nullable=False),
    sa.Column('answer_json', sa.JSON(), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempt.attempt_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_ref_id'], ['quiz_question_ref.ref_id'], ),
    sa.PrimaryKeyConstraint('answer_id'),
    sa.UniqueConstraint('attempt_id', 'question_ref_id', name='uq_quiz_answer_question')
    )
    op.create_index(op.f('ix_quiz_answer_attempt_id'), 'quiz_answer', ['attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_answer_attempt_id'), table_name='quiz_answer')
    op.drop_table('quiz_answer')
    op.drop_index(op.f('ix_poll_answer_student_id'), table_name='poll_answer')
    op.drop_index(op.f('ix_poll_answer_poll_id'), table_name='poll_answer')
    op.drop_table('poll_answer')
    op.drop_index(op.f('ix_quiz_question_ref_quiz_id'), table_name='quiz_question_ref')
    op.drop_table('quiz_question_ref')
    op.drop_index(op.f('ix_quiz_attempt_student_id'), table_name='quiz_attempt')
    op.drop_index(op.f('ix_quiz_attempt_quiz_id'), table_name='quiz_attempt')
    op.drop_table('quiz_attempt')
    op.drop_index(op.f('ix_poll_option_poll_id'), table_name='poll_option')
    op.drop_table('poll_option')
    op.drop_index(op.f('ix_attendance_record_task_id'), table_name='attendance_record')
    op.drop_index(op.f('ix_attendance_record_student_id'), table_name='attendance_record')
    op.drop_table('attendance_record')
    op.drop_index(op.f('ix_assignment_submission_student_id'), table_name='assignment_submission')
    op.drop_index(op.f('ix_assignment_submission_assignment_id'), table_name='assignment_submission')
    op.drop_table('assignment_submission')
    op.drop_index(op.f('ix_assignment_question_ref_assignment_id'), table_name='assignment_question_ref')
    op.drop_table('assignment_question_ref')
    op.drop_index(op.f('ix_quiz_course_id'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_class_id'), table_name='quiz')
    op.drop_table('quiz')
    op.drop_index(op.f('ix_poll_course_id'), table_name='poll')
    op.drop_index(op.f('ix_poll_class_id'), table_name='poll')
    op.drop_table('poll')
    op.drop_index(op.f('ix_attendance_task_lesson_id'), table_name='attendance_task')
    op.drop_index(op.f('ix_attendance_task_course_id'), table_name='attendance_task')
    op.drop_index(op.f('ix_attendance_task_class_id'), table_name='attendance_task')
    op.drop_index('ix_attendance_scope_status', table_name='attendance_task')
    op.drop_table('attendance_task')
    op.drop_index(op.f('ix_assignment_course_id'), table_name='assignment')
    op.drop_index(op.f('ix_assignment_class_id'), table_name='assignment')
    op.drop_table('assignment')
    op.drop_index(op.f('ix_course_lesson_course_id'), table_name='course_lesson')
    op.drop_index(op.f('ix_course_lesson_chapter_id'), table_name='course_lesson')
    op.drop_table('course_lesson')
    op.drop_index(op.f('ix_teaching_teacher_assignment_teacher_id'), table_name='teaching_teacher_assignment')
    op.drop_index(op.f('ix_teaching_teacher_assignment_course_id'), table_name='teaching_teacher_assignment')
    op.drop_index(op.f('ix_teaching_teacher_assignment_class_id'), table_name='teaching_teacher_assignment')
    op.drop_table('teaching_teacher_assignment')
    op.drop_index(op.f('ix_teaching_import_job_class_id'), table_name='teaching_import_job')
    op.drop_table('teaching_import_job')
    op.drop_index(op.f('ix_course_chapter_course_id'), table_name='course_chapter')
    op.drop_table('course_chapter')
    op.drop_index(op.f('ix_class_membership_student_id'), table_name='class_membership')
    op.drop_index(op.f('ix_class_membership_class_id'), table_name='class_membership')
    op.drop_table('class_membership')
    op.drop_index(op.f('ix_class_course_course_id'), table_name='class_course')
    op.drop_index(op.f('ix_class_course_class_id'), table_name='class_course')
    op.drop_table('class_course')
    op.drop_index(op.f('ix_course_owner_teacher_id'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_class_owner_teacher_id'), table_name='class')
    op.drop_table('class')
    # ### end Alembic commands ###
