import { expect, test } from '@playwright/test'
import ExcelJS from 'exceljs'


test('G1/G2 与学生管理、投票、作业测验真实主链', async ({ page, browser }, testInfo) => {
  test.skip(process.env.E2E_REAL_API !== '1', '仅在真实后端与 MySQL 验收时运行')
  const workbook = new ExcelJS.Workbook()
  const sheet = workbook.addWorksheet('学生导入')
  sheet.addRow(['学号*', '姓名*', '班级', '手机号（可选）', '邮箱（可选）'])
  const run = Date.now().toString().slice(-7)
  for (let index = 1; index <= 43; index += 1) sheet.addRow([`${run}${String(index).padStart(2, '0')}`, `浏览器学生${index}`, '网络安全 2301 班', '', ''])
  const filePath = testInfo.outputPath('students-43.xlsx')
  await workbook.xlsx.writeFile(filePath)
  const badWorkbook = new ExcelJS.Workbook()
  const badSheet = badWorkbook.addWorksheet('学生导入')
  badSheet.addRow(['学号*', '姓名*', '班级', '手机号（可选）', '邮箱（可选）'])
  badSheet.addRow([`${run}01`, '重复学生', '网络安全 2301 班', '', ''])
  badSheet.addRow(['=2+2', '公式风险', '网络安全 2301 班', '', ''])
  const badFilePath = testInfo.outputPath('students-errors.xlsx')
  await badWorkbook.xlsx.writeFile(badFilePath)

  await page.goto('/courses')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
  await page.getByRole('button', { name: '＋ 新建课程' }).click()
  await expect(page.getByTestId('message')).toContainText('课程已创建')
  await page.getByRole('button', { name: '＋ 建班' }).click()
  await expect(page.getByTestId('message')).toContainText('班级已创建')
  await page.getByLabel('选择学生名单').setInputFiles(filePath)
  await page.getByRole('button', { name: '导入学生' }).click()
  await expect(page.getByTestId('message')).toContainText('成功 43 人')
  await page.getByLabel('选择学生名单').setInputFiles(badFilePath)
  await page.getByRole('button', { name: '导入学生' }).click()
  await expect(page.getByTestId('message')).toContainText('失败 2 人')
  const errorDownload = page.waitForEvent('download')
  await page.getByTestId('import-error-download').click()
  expect((await errorDownload).suggestedFilename()).toBe('student-import-errors.xlsx')

  await page.goto('/teacher-students')
  await expect(page.getByRole('heading', { name: '学生管理' })).toBeVisible()
  await expect(page.getByText('共 43 人')).toBeVisible()
  await page.getByPlaceholder('输入姓名或学号').fill('浏览器学生1')
  await page.getByRole('button', { name: '查询' }).click()
  await expect(page.getByRole('cell', { name: '浏览器学生1', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '查看详情' }).first().click()
  await expect(page.getByRole('dialog', { name: '学生详情' })).toContainText('数据待汇总')
  await page.getByRole('button', { name: '关闭' }).click()

  await page.goto('/attendance-management')
  await page.getByRole('button', { name: '发布签到' }).click()
  await expect(page.getByTestId('attendance-message')).toContainText('签到已发布')
  const signUrl = await page.getByTestId('attendance-link').getAttribute('href')
  const studentId = await page.evaluate(() => localStorage.getItem('yk-student-id'))
  expect(signUrl).toContain('/student-attendance/')
  expect(studentId).toBeTruthy()
  const studentContext = await browser.newContext()
  await studentContext.addInitScript(id => localStorage.setItem('yk-student-id', id), studentId!)
  const studentPage = await studentContext.newPage()
  await studentPage.goto(signUrl!)
  await expect(studentPage.getByText('RSA 数字签名课堂签到')).toBeVisible()
  await studentPage.getByRole('button', { name: '立即签到' }).click()
  await expect(studentPage.getByText('签到成功')).toBeVisible()
  await studentContext.close()
  await page.goto('/attendance-management')
  await page.getByRole('button', { name: '刷新结果' }).click()
  await expect(page.locator('.kpi').nth(1)).toContainText('1')

  await page.goto('/teacher-assignments')
  await page.getByRole('button', { name: '发布投票' }).click()
  await expect(page.getByTestId('work-message')).toContainText('投票已发布')
  await page.getByRole('button', { name: '＋ 发布课后作业与小测' }).click()
  await expect(page.getByTestId('work-message')).toContainText('作业与测验已发布')
  await page.goto('/student-quiz')
  await page.getByRole('button', { name: '提交投票、作业与测验' }).click()
  await expect(page.getByTestId('student-work-message')).toContainText('均已提交')
  await page.goto('/teacher-assignments')
  await page.getByRole('button', { name: '查看统计' }).click()
  await expect(page.getByText('1 人')).toBeVisible()
})
